- .gitignore
> [전우진] 수정된 gitignore 파일 업로드

- .gitignore
- clothingShoppingMall/src/main/resources/db.properties
- clothingShoppingMall/src/main/resources/log4j.xml
- clothingShoppingMall/src/main/resources/mybatis-config.xml
> [전우진] .gitignore 최신화

- .classpath
- .gitignore
- .project
.gitignore 적용 및 nest되어 import되는 폴더 2개 1개만 잡히도록 설정
> [전우진] Apply .gitignore

- clothingShoppingMall/.classpath
- clothingShoppingMall/src/main/java/com/hi/clothingStore/controller/MemberController.java
- clothingShoppingMall/src/main/java/com/hi/clothingStore/dao/MemberDAO.java
- clothingShoppingMall/src/main/resources/mapper/member.xml
- clothingShoppingMall/src/main/webapp/WEB-INF/views/memberUpdate.jsp
- clothingShoppingMall/src/main/webapp/member.jsp
- clothingShoppingMall/src/main/webapp/memberCre.jsp
- clothingShoppingMall/src/main/webapp/memberDelete.jsp
- clothingShoppingMall/src/main/webapp/memberUpdate.jsp
- clothingShoppingMall/src/main/webapp/myPage.jsp
> [오진희]회원수정 업데이트

- clothingShoppingMall/src/main/java/com/hi/clothingStore/dao/LikeDAO.java
- clothingShoppingMall/src/main/java/com/hi/clothingStore/service/ProductListService.java
- clothingShoppingMall/src/main/resources/mapper/like.xml
> [신상석]전체 상품 like 수 업데이트 진행 중

- .project
.project 파일 수정을 통한 git repo명과 clone/pull 폴더명 통일
> [전우진] .project 파일 수정

- .classpath
Solved src/test/java folder build missing
> [전우진] build missing 해결

- .classpath
- .project
- src/main/java/com/hi/clothingStore/controller/MemberController.java
- src/main/java/com/hi/clothingStore/dao/MemberDAO.java
- src/main/resources/mapper/member.xml
- src/main/webapp/WEB-INF/views/memberNo.jsp
- src/main/webapp/member.jsp
- src/main/webapp/memberCre.jsp
- src/main/webapp/memberUpdate.jsp
[오진희]id,pw중복체크 구현+회원수정, 회원가입 전체적으로 보완
> [오진희]id,pw중복체크 구현

- .classpath
- .project
- src/main/java/com/hi/clothingStore/controller/ProductListController.java
- src/main/java/com/hi/clothingStore/dao/LikeDAO.java
- src/main/java/com/hi/clothingStore/dao/ProductListDAO.java
- src/main/java/com/hi/clothingStore/service/ProductListService.java
- src/main/resources/mapper/like.xml
- src/main/resources/mapper/productlist.xml
- src/main/resources/mybatis-config.xml
- src/main/webapp/WEB-INF/views/productList.jsp
- src/main/webapp/WEB-INF/views/productOne.jsp
> [신상석] 상품 like 전체 업데이트 기능 완료

- src/main/java/com/hi/clothingStore/controller/ServiceCenterFaqController.java
- src/main/webapp/WEB-INF/views/faqList.jsp
- src/main/webapp/WEB-INF/views/serviceFaqUpdate1.jsp
- src/main/webapp/WEB-INF/views/serviceFaqUpdate2.jsp
> [유수빈] faq 수정삭제기능 체크박스

- .classpath
- src/main/java/com/hi/clothingStore/controller/ReviewController.java
- src/main/java/com/hi/clothingStore/vo/ReviewListVO.java
- src/main/java/com/hi/clothingStore/vo/ReviewVO.java
- src/main/resources/mapper/review.xml
- src/main/resources/mybatis-config.xml
- src/main/webapp/reviewList.jsp
<작업 내용>
1. 구매 후기 작성 구현 완료 (수정/삭제 버튼 작업 중)
2. 서버 동작 시 404 error 페이지 표시되며 동작 불가했던 오류 해결
> [전우진] 구매 후기 작성 구현 완료 및 서버 동작 불가 오류 해결

- src/main/java/com/hi/clothingStore/controller/ReviewController.java
- src/main/resources/mapper/review.xml
- src/main/webapp/reviewList.jsp
<작업 내용>
- 후기 삭제 구현
- 후기 삭제 과정 주석으로 표기
- 후기 목록 날짜/시간 표기법 변경
- 날짜/시간 변환 함수의 3가지 표현법의 차이점 주석으로 표기
> [전우진] 구매 후기 삭제 부분 구현 완료 및 후기 목록 날짜/시간 표기법 변경

- .classpath
- src/main/java/com/hi/clothingStore/controller/ReviewController.java
- src/main/resources/mapper/review.xml
- src/main/webapp/reviewList.jsp
<작업 내용>
1. 무분별한 select * from 사용을 지양해야 하는 이유 주석 표기
2. 접근 제한 함수에 대한 설명 주석 표기
3. 추후 작성 부분에 관하여 주석 표기
4. 후기 수정 부분 관련 ReviewController 수정
> [전우진] 작업 관련 주석 표기와 후기 수정 부분 작업

- .classpath
- src/main/java/com/hi/clothingStore/service/ProductListService.java
- src/main/webapp/WEB-INF/views/productOne.jsp
[신상석] IndexOutOfBoundsException 예외처리
> [신상석] IndexOutOfBoundsException 예외처리

- src/main/java/com/hi/clothingStore/controller/MemberController.java
- src/main/webapp/WEB-INF/views/memberCheck.jsp
- src/main/webapp/WEB-INF/views/memberCreate.jsp
- src/main/webapp/WEB-INF/views/memberOk.jsp
- src/main/webapp/WEB-INF/views/memberUpdate.jsp
- src/main/webapp/member.jsp
- src/main/webapp/memberCre.jsp
- src/main/webapp/memberTop.jsp
- src/main/webapp/memberUpdate.jsp
> [오진희]회원가입,수정 조건 구현 버튼 생성

- .classpath
- src/main/java/com/hi/clothingStore/controller/MemberController.java
- src/main/webapp/WEB-INF/views/member.jsp
- src/main/webapp/reviewList.jsp
- src/main/webapp/top.jsp
> [오진희]member.jsp경로수정

- src/main/java/com/hi/clothingStore/vo/ReviewListVO.java
- src/main/java/com/hi/clothingStore/vo/ReviewVO.java
review_score 타입 수정: float --> decimal(2,1)
FLOAT 및 REAL 테이터 형식은 근사 데이터 형식이어서 정확한 값을 저장하지 않고
가장 가까운 근사값을 저장하기 때문에 나누기 등의 계산을 할때 정확한 값이
출력되지 않고 근사값을 출력된다.
평점과 총 평균 평점을 구해야 하므로 float 대신 decimal(2,1)로 수정하였다
> [전우진] ReviewVO, ReviewListVO score type 수정

- .classpath
- src/main/java/com/hi/clothingStore/controller/MemberController.java
- src/main/webapp/WEB-INF/views/productAdd.jsp
- src/main/webapp/WEB-INF/views/productOne.jsp
- src/main/webapp/basket.jsp
- src/main/webapp/resources/css/basket.css
- src/main/webapp/resources/js/basket.js
> [신상석]장바구니 css 수정

- .classpath
- src/main/java/com/hi/clothingStore/controller/ReviewController.java
- src/main/webapp/reviewList.jsp
- src/main/webapp/top.jsp
> [전우진] 후기 수정 구현

- .classpath
- src/main/webapp/WEB-INF/views/productOne.jsp
- src/main/webapp/basket.jsp
> [신상석]장바구니 css 복구

- .classpath
- src/main/java/com/hi/clothingStore/controller/LikeController.java
- src/main/java/com/hi/clothingStore/controller/ProductListController.java
- src/main/java/com/hi/clothingStore/vo/ProductListVO3.java
- src/main/resources/mapper/like.xml
- src/main/webapp/WEB-INF/views/productOne.jsp
- src/main/webapp/WEB-INF/views/publicData.jsp
- src/main/webapp/basket.jsp
- src/main/webapp/myLike.jsp
- src/main/webapp/resources/js/basket.js
- src/main/webapp/top.jsp
> [신상석] mvc 경로 설정

- src/main/java/com/hi/clothingStore/controller/MemberController.java
- src/main/java/com/hi/clothingStore/dao/MemberDAO.java
- src/main/resources/mapper/member.xml
- src/main/webapp/WEB-INF/views/member.jsp
- src/main/webapp/WEB-INF/views/memberOk.jsp
- src/main/webapp/WEB-INF/views/memberUnCreate.jsp
- src/main/webapp/WEB-INF/views/memberUnlogin.jsp
- src/main/webapp/WEB-INF/views/myPage.jsp
- src/main/webapp/memberDelete.jsp
- src/main/webapp/memberUpdate.jsp
- src/main/webapp/top.jsp
[오진희]myPage구현,top.jsp로그인/로그아웃구현
> [오진희]myPage구현

- .classpath
- src/main/java/com/hi/clothingStore/controller/ReviewController.java
- src/main/java/com/hi/clothingStore/dao/ReviewDAO.java
- src/main/java/com/hi/clothingStore/dao/ReviewDAOImpl.java
- src/main/java/com/hi/clothingStore/service/ReviewService.java
- src/main/java/com/hi/clothingStore/service/ReviewServiceImpl.java
- src/main/resources/mapper/review.xml
- src/main/webapp/reviewList.jsp
후기 수정 오류 해결 및 평점 구현
1. 후기 작성 시 입력 창 초기화 구현
2. 후기 수정 시 버튼 미동작 해결
3. 후기 평점 select/option으로 구현
4. 후기 목록에 평점 보여주도록 구현
> [전우진] 후기 수정 오류 해결 및 평점 구현

- .classpath
- src/main/webapp/WEB-INF/views/faqListView.jsp
- src/main/webapp/WEB-INF/views/serviceNoticeOne.jsp
- src/main/webapp/WEB-INF/views/serviceOne.jsp
- src/main/webapp/serviceMain.jsp
> [유수빈]FaQ 완료

- .classpath
- src/main/java/com/hi/clothingStore/controller/ProductListController.java
- src/main/java/com/hi/clothingStore/dao/ProductListDAO.java
- src/main/java/com/hi/clothingStore/restAPI/LikeRestAPI.java
- src/main/java/com/hi/clothingStore/restAPI/ProductRestAPI.java
- src/main/java/com/hi/clothingStore/vo/ProductListVO2.java
- src/main/java/com/hi/clothingStore/vo/ProductListVO4.java
- src/main/resources/mapper/productlist.xml
- src/main/resources/mybatis-config.xml
- src/main/webapp/WEB-INF/views/myPage.jsp
- src/main/webapp/WEB-INF/views/orderHistory.jsp
- src/main/webapp/WEB-INF/views/purchaseList.jsp
> [신상석]구매 페이지 완료 및 결제 이력 구현 중

- .classpath
- src/main/java/com/hi/clothingStore/controller/ReviewController.java
- src/main/webapp/reviewList.jsp
총 평균 평점 구현 및 평점 표시 오류 해결
1. select avg sql을 통한 총 평균 평점 구현
2. success 시 평점 표시, error 시 '집계된 평점이 없습니다' 문구 출력
3. select box로 구현된 평점에서 별 모양의 별점으로 후기 작성 시 표시되도록 구현
> [전우진] 총 평균 평점 구현 및 평점 표시 오류 해결

- src/main/java/com/hi/clothingStore/controller/LikeController.java
- src/main/java/com/hi/clothingStore/controller/ReviewController.java
- src/main/java/com/hi/clothingStore/restAPI/LikeRestAPI.java
- src/main/webapp/WEB-INF/views/myLikeList.jsp
- src/main/webapp/WEB-INF/views/productOne.jsp
- src/main/webapp/WEB-INF/views/purchaseList.jsp
- src/main/webapp/myLikeList.jsp
- src/main/webapp/reviewList.jsp
- src/main/webapp/top.jsp
> [신상석] MyLike 페이지 구현

- .classpath
- pom.xml
- src/main/java/com/hi/clothingStore/controller/ReviewController.java
- src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- src/main/webapp/resources/css/reviewStyle.css
- src/main/webapp/reviewList.jsp
reviewList.jsp 파일 css 분리
reviewList.jsp를 reviewList.jsp와 reviewStyle.css로 분리
> [전우진] reviewList.jsp 파일 css 분리

- src/main/java/com/hi/clothingStore/controller/MemberController.java
- src/main/java/com/hi/clothingStore/dao/MemberDAO.java
- src/main/resources/mapper/member.xml
- src/main/webapp/WEB-INF/views/memberAdDelete.jsp
- src/main/webapp/WEB-INF/views/memberAdmin.jsp
- src/main/webapp/WEB-INF/views/memberCheck.jsp
- src/main/webapp/WEB-INF/views/memberCreate.jsp
- src/main/webapp/WEB-INF/views/memberDelete.jsp
- src/main/webapp/WEB-INF/views/memberOne.jsp
- src/main/webapp/WEB-INF/views/memberUnlogin.jsp
- src/main/webapp/WEB-INF/views/myPage.jsp
- src/main/webapp/memberCre.jsp
- src/main/webapp/memberDelete.jsp
- src/main/webapp/memberUpdate.jsp
- src/main/webapp/top.jsp
[오진희]관리자페이지구현,회원전체검색,상세검색crud구현
> [오진희]관리자페이지구현,회원전체검색,상세검색crud구현

- .classpath
- src/main/java/com/hi/clothingStore/controller/ProductListController.java
- src/main/java/com/hi/clothingStore/service/ProductListService.java
- src/main/java/com/hi/clothingStore/vo/ProductPageVO.java
- src/main/resources/mapper/like.xml
- src/main/webapp/WEB-INF/views/productList.jsp
- src/main/webapp/top.jsp
> [신상석] 기능테스트 완료

- .classpath
- pom.xml
- src/main/java/com/hi/clothingStore/controller/ReviewController.java
- src/main/java/com/hi/clothingStore/vo/ReviewListVO.java
- src/main/java/com/hi/clothingStore/vo/ReviewVO.java
- src/main/resources/root-context.xml
- src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/reviewList.jsp
후기 작성 시 이미지 첨부 가능하도록 구현 작업 중..
코드 작성 후 오류 해결 중에 있습니다
> [전우진] 후기 작성 시 이미지 첨부 구현 중

- .classpath
- src/main/java/com/hi/clothingStore/controller/ProductListController.java
- src/main/java/com/hi/clothingStore/dao/ProductListDAO.java
- src/main/java/com/hi/clothingStore/restAPI/ProductRestAPI.java
- src/main/java/com/hi/clothingStore/vo/ProductListVO2.java
- src/main/resources/mapper/productlist.xml
- src/main/webapp/WEB-INF/views/myPage.jsp
- src/main/webapp/WEB-INF/views/productOne.jsp
> [신상석] 세션 진행 중

- src/main/java/com/hi/clothingStore/controller/MemberController.java
- src/main/java/com/hi/clothingStore/dao/MemberDAO.java
- src/main/java/com/hi/clothingStore/vo/MemberVO.java
- src/main/resources/mapper/member.xml
- src/main/webapp/WEB-INF/views/member.jsp
- src/main/webapp/WEB-INF/views/memberAdmin.jsp
- src/main/webapp/WEB-INF/views/memberOne.jsp
- src/main/webapp/WEB-INF/views/myPage.jsp
- src/main/webapp/memberUpdate.jsp
- src/main/webapp/top.jsp
> [member]관리자회원검색구현

- src/main/webapp/WEB-INF/views/myPage.jsp
- src/main/webapp/top.jsp
> [member]마이페이지수정,top.jsp수정

- .classpath
- src/main/java/com/hi/clothingStore/controller/ReviewController.java
- src/main/java/com/hi/clothingStore/dao/ReviewDAO.java
- src/main/java/com/hi/clothingStore/dao/ReviewDAOImpl.java
- src/main/java/com/hi/clothingStore/service/ReviewService.java
- src/main/java/com/hi/clothingStore/service/ReviewServiceImpl.java
- src/main/resources/mapper/review.xml
- src/main/resources/root-context.xml
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/reviewList.jsp
- 후기 이미지 업로드 구현
- 후기 목록 이미지 미리보기 구현
- git pull 후 reviewController에서 uploadPath2 경로 수정 (C에 받았으면 C로, D로 받았으면 D로)
- eclipse - window - preferences - general - workspace - Refresh using native hooks or polling 체크 후 apply and close
> [전우진] 후기 이미지 업로드 및 후기 목록 이미지 미리보기 구현

- .classpath
- src/main/java/com/hi/clothingStore/controller/ProductListController.java
- src/main/java/com/hi/clothingStore/dao/ProductListDAO.java
- src/main/java/com/hi/clothingStore/restAPI/LikeRestAPI.java
- src/main/java/com/hi/clothingStore/restAPI/ProductRestAPI.java
- src/main/resources/mapper/productlist.xml
- src/main/webapp/WEB-INF/views/memberOne.jsp
- src/main/webapp/WEB-INF/views/productList.jsp
- src/main/webapp/WEB-INF/views/productOne.jsp
> [신상석]nullException 재수정

- .classpath
- src/main/webapp/WEB-INF/views/productList.jsp
[신상석]메인 페이지 부트스트랩 적용 및 상품 중앙 배치
> [신상석]메인 페이지 부트스트랩 적용 및 상품 중앙 배치

- .classpath
- src/main/webapp/WEB-INF/views/myPage.jsp
- src/main/webapp/WEB-INF/views/productInsert.jsp
- src/main/webapp/WEB-INF/views/productList.jsp
- src/main/webapp/WEB-INF/views/productNo.jsp
- src/main/webapp/WEB-INF/views/productOne.jsp
- src/main/webapp/WEB-INF/views/productSuccess.jsp
- src/main/webapp/WEB-INF/views/productUp.jsp
- src/main/webapp/WEB-INF/views/purchaseList.jsp
> [신상석] 상품 part 부트스트랩 적용 완료. 

- .classpath
- src/main/webapp/reviewList.jsp
- src/main/webapp/statistics.jsp
통계 및 구매 후기 페이지 수정
1. 통계 및 구매 후기 주석 추가
2. 통계 페이지 제목 추가
> [전우진] 통계 및 구매 후기 페이지 주석 추가, 통계 제목 추가

- .classpath
- src/main/webapp/resources/assets/css/templatemo-eduwell-style.css
- src/main/webapp/resources/css/reviewStyle.css
- src/main/webapp/reviewList.jsp
- src/main/webapp/statistics.jsp
후기 페이지 css 조정 및 메뉴 상단 바 폰트 크기 조절
1. 후기 페이지 css 조정 - 후기 작성 폼 위치 조정
2. 상단 바 폰트 크기 조절
> [전우진] 후기 페이지 css 조정

- .classpath
- src/main/webapp/reviewList.jsp
작성자는 수정만 가능하고 관리자가 삭제만 가능한 후기를 만들고자 함
작성자는 수정만 가능했으나 관리자가 삭제 버튼을 눌렀을 경우 작성자가 아니라 수정이 불가능하다는 알림창이 뜨게 됨
작성자가 수정과 삭제를 하도록 변경
> [전우진] 후기 삭제 알고리즘 수정

- .classpath
- src/main/resources/mapper/member.xml
- src/main/webapp/WEB-INF/views/member.jsp
- src/main/webapp/WEB-INF/views/memberAdmin.jsp
- src/main/webapp/WEB-INF/views/memberNo.jsp
- src/main/webapp/WEB-INF/views/memberOne.jsp
- src/main/webapp/WEB-INF/views/myPage.jsp
- src/main/webapp/memberCre.jsp
- src/main/webapp/memberDelete.jsp
- src/main/webapp/memberUpdate.jsp
- src/main/webapp/resources/css/member.css
> [member]css수정

- .classpath
- src/main/java/com/hi/clothingStore/controller/ProductListController.java
- src/main/webapp/WEB-INF/views/productOne.jsp
- src/main/webapp/WEB-INF/views/publicData.jsp
- src/main/webapp/top.jsp
> 신상석[공공데이터 오픈API출력]

- .classpath
- src/main/java/com/hi/clothingStore/controller/ReviewController.java
- src/main/java/com/hi/clothingStore/dao/ReviewDAO.java
- src/main/java/com/hi/clothingStore/dao/ReviewDAOImpl.java
- src/main/java/com/hi/clothingStore/service/ReviewService.java
- src/main/java/com/hi/clothingStore/service/ReviewServiceImpl.java
- src/main/java/com/hi/clothingStore/vo/ReviewListVO.java
- src/main/java/com/hi/clothingStore/vo/ReviewVO.java
- src/main/webapp/reviewList.jsp
- src/main/webapp/statistics.jsp
> [전우진] 주석 간결화

- src/main/webapp/resources/css/reviewStyle.css
- src/main/webapp/reviewList.jsp
템플릿 css 와의 순서 오류로 비회원 시 로그인 페이지로 이동 문구 미표시
문구 css에 z-index: -1; 추가
> [전우진] 비회원 시 로그인 페이지로 이동 문구 미표시 해결

- .classpath
- src/main/webapp/reviewList.jsp
후기 목록 무한 스크롤 구현
[무한 스크롤 vs 페이지네이션 vs '더보기' 버튼](https://brunch.co.kr/@blackindigo-red/13)
> [전우진] 후기 목록 무한 스크롤 구현

- .classpath
- src/main/java/com/hi/clothingStore/controller/MemberController.java
- src/main/java/com/hi/clothingStore/dao/MemberDAO.java
- src/main/resources/mapper/member.xml
- src/main/webapp/WEB-INF/views/memberAdUpdate.jsp
- src/main/webapp/WEB-INF/views/memberOne.jsp
> [member]오류수정

- .classpath
- src/main/java/com/hi/clothingStore/vo/ReviewListVO.java
- src/main/java/com/hi/clothingStore/vo/ReviewVO.java
- src/main/resources/mapper/review.xml
- src/main/webapp/reviewList.jsp
긍정 / 부정 후기에 대하여 emoji로 표현
- 긍정인 경우 😊로 표현
- 부정인 경우 😡로 표현
> [전우진] 긍정/부정 후기에 대한 이모지 표시

- .classpath
- src/main/webapp/reviewList.jsp
후기 목록
후기 목록에서 이미지가 중복되어 표시되어 수정
> [전우진] 후기 목록 이모지 중복 표시 수정

- .classpath
- .project
- src/main/webapp/WEB-INF/views/myPage.jsp
- src/main/webapp/resources/css/member.css
[member]추천시스템구현&이미지추가&상세페이지로이동
> [member]추천시스템구현

- .project
- src/main/webapp/WEB-INF/views/myPage.jsp
> [member]추천시스템오류수정

- .classpath
- src/main/webapp/WEB-INF/views/member.jsp
- src/main/webapp/WEB-INF/views/memberAdmin.jsp
- src/main/webapp/WEB-INF/views/memberCheck.jsp
- src/main/webapp/WEB-INF/views/memberNo.jsp
- src/main/webapp/WEB-INF/views/memberOne.jsp
- src/main/webapp/WEB-INF/views/myPage.jsp
- src/main/webapp/memberCre.jsp
- src/main/webapp/memberDelete.jsp
- src/main/webapp/memberUpdate.jsp
- src/main/webapp/resources/css/member.css
> [member]css수정&django와url연결
